### ISSUE TITLE
Cannot increase the maximum size of an upload

### ISSUE THREAD

**Issue by wsw70** [eikek/sharry#1529]
According to the documentation, `max-size` sets the maximum size for an upload (1.5 GB by default). I tried to change it in my docker deployment by using the relevant env variable (sharry is behind a reverse proxy, namely Traefik):

```yaml
services:
  sharry:
    command: /opt/conf/sharry.conf
    image: eikek0/sharry:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - conf:/opt/conf
      - data:/data
    environment:
      - SHARRY_MAX_SIZE="10G"
      - SHARRY_CHUNK_SIZE="50M"
volumes:
  conf: null
  data: null
```

`SHARRY_MAX_SIZE` does not change the default, 1.5G is displayed in the upload section and it is indeed the maximum

**Comment by eikek** [comment]
That is strange. I just tried it here and it works. This is the compose file I used:
```yaml
version: '3.7'
services:
  restserver:
    image: eikek0/sharry:latest
    container_name: sharry
    command: /opt/sharry.conf
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/sharry.conf:/opt/sharry.conf
    environment:
      - SHARRY_BACKEND_SHARE_MAX_SIZE=23G
      - SHARRY_BACKEND_AUTH_FIXED_ENABLE=true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.0
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - PGUSER=dbuser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "dbname"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 15s
volumes:
  postgres_data:
```
