### ISSUE TITLE
postgres_db   FATAL:  database "dbuser" does not exist

### ISSUE THREAD

**Issue by GitNees** [eikek/sharry#1566]
Hi,

Just running the app with docker, but this error keeps popping up.
I googled, but cant find any info.

postgres_db   | 2024-12-19 11:41:37.292 UTC [199] FATAL:  database "dbuser" does not exist
postgres_db   | 2024-12-19 11:41:52.409 UTC [207] FATAL:  database "dbuser" does not exist
postgres_db   | 2024-12-19 11:42:07.534 UTC [215] FATAL:  database "dbuser" does not exist
postgres_db   | 2024-12-19 11:42:22.655 UTC [223] FATAL:  database "dbuser" does not exist

Anything that could case a problem?

**Comment by rkdover** [comment]
I have this issue as well, unsure of how to resolve it.

**Comment by rkdover** [comment]
You know, going back to the last human commit of that file, it still throws the same error. I wonder if there's some dbuser config you need to do manually that isn't mentioned?

**Comment by eikek** [comment]
From what I know, the user is created by the postgres image startup script. Perhaps that changed at some version? You can always create the user manually, though.

**Comment by zupermann** [comment]
I encountered the same problem. 
I believe that in my case the issue was that on the default docker network there was another Postgres container (of an entire different service) with the same name and Sharry connected to it instead of own Postgres container. 

To rule this issue out you can test by stopping all other Postgres containers before starting Sharry. 

If the same issue is confirmed you can just change the container name from docker-compose.yml

**Comment by michnovka** [comment]
I fixed this by updating the test case:

```yaml
  db:
    image: postgres:17.1
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - PGUSER=dbuser
    healthcheck:
      test: pg_isready -d dbname
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 15s
```

@eikek can you please review and possibly fix this in main repo?
